## NBA資料集
### 設計說明：
1. 請使用線性迴歸預測方式撰寫程式，讀取NBApoints.csv，此資料收集了NBA球員的資訊。
2. NBApoints.csv其中每一行都包含用逗號分隔的字串格式等共30個欄位，資料集的欄位簡易說明如下，其餘省略。

欄位名稱 |說明
--------|----
Rk	|排名
Player	|球員
Pos	|守備位置
Age	|年齡
Tm	|隊名
3. 請將Pos欄位及Tm欄位資料轉換為數值，以利進行後續處理。
4. 接著建立機器學習模型並預測。以Pos、Age、2P、Tm四個欄位進行訓練。
5. 運用sklearn.linear_model.score，計算出R-squared與P-value。
### 請依序回答下列問題：


1. 輸入測試資料[5,28,10,11]，請填入預測NBA球員的三分球得球數（四捨五入取至小數點後第四位）？
2. 請填入R-squared 之值的模型解釋力（四捨五入取至小數點後第四位）？
3. 檢定變數的顯著性，以Pos的 P-value （P值）是否小於 0.05（信心水準 95%）來判定。Pos的P值顯著填入Y，不顯著填入N？
4. 檢定變數的顯著性，以Age的P-value （P值）是否小於 0.05（信心水準 95%）來判定。Age的P值顯著填入Y，不顯著填入N？

In [2]:
# 導入所需套件
import pandas as pd
import numpy as np
from sklearn import preprocessing, linear_model
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

In [3]:
# 匯入原始資料並檢視相關資訊
NBApoints_data= pd.read_csv("NBApoints.csv")
NBApoints_data.info()
NBApoints_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 476 entries, 0 to 475
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rk      476 non-null    int64
 1   Player  476 non-null    object
 2   Pos     476 non-null    object
 3   Age     476 non-null    int64
 4   Tm      476 non-null    object
 5   G       476 non-null    int64
 6   GS      476 non-null    int64
 7   MP      476 non-null    float64
 8   FG      476 non-null    float64
 9   FGA     476 non-null    float64
 10  FG%     475 non-null    float64
 11  3P      476 non-null    float64
 12  3PA     476 non-null    float64
 13  3P%     433 non-null    float64
 14  2P      476 non-null    float64
 15  2PA     476 non-null    float64
 16  2P%     473 non-null    float64
 17  eFG%    475 non-null    float64
 18  FT      476 non-null    float64
 19  FTA     476 non-null    float64
 20  FT%     462 non-null    float64
 21  ORB     476 non-null    float64
 22  DRB     476 non-null    float64
 23  TRB     476 non-null    float64
 24  AST     476 non-null    float64
 25  STL     476 non-null    float64
 26  BLK     476 non-null    float64
 27  TOV     476 non-null    float64
 28  PF      476 non-null    float64
 29  PS/G▼   476 non-null    float64
dtypes: float64(23), int64(4), object(3)
memory usage: 111.7+ KB

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PS/G▼
count,476.000000,476.000000,476.000000,476.000000,476.000000,476.000000,476.000000,475.000000,476.000000,476.000000,...,462.000000,476.000000,476.000000,476.000000,476.000000,476.000000,476.000000,476.000000,476.000000,476.000000
mean,238.500000,26.594538,54.785714,25.840336,20.160084,3.113235,6.951891,0.444091,0.688025,1.963866,...,0.741426,0.870378,2.754832,3.620378,1.826050,0.653361,0.415126,1.146849,1.744538,8.349370
std,137.553626,4.382440,24.274576,29.413419,9.218341,2.053724,4.420795,0.085532,0.713570,1.862538,...,0.129695,0.775428,1.769210,2.407572,1.756933,0.438861,0.448180,0.782957,0.742706,5.652556
min,1.000000,19.000000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,119.750000,23.000000,37.000000,1.000000,13.000000,1.500000,3.500000,0.404500,0.100000,0.300000,...,0.682500,0.300000,1.500000,1.900000,0.675000,0.300000,0.100000,0.600000,1.200000,4.000000
50%,238.500000,26.000000,62.000000,10.000000,19.950000,2.700000,5.950000,0.439000,0.500000,1.500000,...,0.756000,0.600000,2.350000,3.100000,1.300000,0.600000,0.300000,0.900000,1.800000,7.000000
75%,357.250000,29.000000,76.000000,53.000000,28.025000,4.400000,9.600000,0.483000,1.100000,3.125000,...,0.827000,1.200000,3.600000,4.800000,2.325000,0.900000,0.500000,1.500000,2.200000,11.625000
max,476.000000,39.000000,82.000000,82.000000,42.000000,10.200000,20.500000,1.000000,5.100000,11.200000,...,1.000000,4.900000,10.300000,14.800000,11.700000,2.100000,3.700000,4.600000,6.000000,30.100000

## NBA資料集中的欄位意義

資料名	|英文全名|含義 |資料名	|英文全名|含義
----|------|----|----|------|----
Rk |Rank	|排名|G |Games	|參與的比賽場數（都為82場）
GS |Games Start |先發比賽場數|MP |Minutes Played	|平均每場比賽進行的時間(分鐘)
FG|Field Goals	|投球命中次數|FGA|Field Goal Attempts	|投射次數
FG%|Field Goal Percentage	|投球命中率|3P|3-Point Field Goals	|三分球命中次數
3PA|3-Point Field Goal Attempts	|三分球投射次數|3P%|3-Point Field Goal Percentage	|三分球命中率
2P|2-Point Field Goals	|二分球命中次數|2PA|2-point Field Goal Attempts	|二分球投射次數
2P%|2-Point Field Goal Percentage	|二分球命中率|eFG%|effective field goal percentage |有效命中率
FT|Free Throws	|罰球命中次數|FTA|Free Throw Attempts	|罰球投射次數
FT%|Free Throw Percentage	|罰球命中率|ORB|Offensive Rebounds	|進攻籃板球
DRB|Defensive Rebounds	|防守籃板球|TRB|Total Rebounds	|籃板球總數
AST|Assists	|助攻|STL|Steals	|偷球(抄截)
BLK |Blocks	|封阻(火鍋)|TOV |Turnovers	|失誤
PF |Personal Fouls	|個人犯規|PTS |Points	|得分

In [4]:
# 將Pos欄位及Tm欄位資料轉換為數值
label_encoder_conver = preprocessing.LabelEncoder()
Pos_encoder_value = label_encoder_conver.fit_transform(NBApoints_data["Pos"])

label_encoder_conver = preprocessing.LabelEncoder()
Tm_encoder_value = label_encoder_conver.fit_transform(NBApoints_data["Tm"])
# 列印更新後資料
print(Pos_encoder_value)
print("\n")
print(Tm_encoder_value)

[3 5 4 0 4 3 1 5 3 4 3 5 4 1 4 3 5 3 5 4 0 3 3 4 3 5 4 3 1 5 3 1 0 5 0 1 4
 0 5 4 1 1 3 3 0 0 1 3 5 0 1 5 3 5 4 3 0 1 5 5 5 5 0 1 4 1 5 5 5 1 5 4 0 3
 4 1 3 3 1 5 5 5 0 4 0 5 3 4 5 4 4 3 3 0 4 0 0 4 1 3 1 5 5 1 5 4 1 3 0 1 3
 3 4 4 1 4 4 5 1 4 4 3 4 1 4 5 0 5 4 3 4 3 3 3 3 4 5 5 1 3 5 0 1 0 4 5 0 3
 4 0 0 3 4 3 1 5 5 5 4 5 5 5 3 4 0 5 4 3 1 1 5 0 0 3 0 3 5 5 3 0 5 3 5 5 1
 1 0 0 1 3 0 5 1 3 5 5 1 3 4 0 1 3 4 0 4 1 0 1 5 5 1 5 3 3 3 3 1 3 3 0 5 1
 1 3 5 4 5 1 4 0 4 4 5 0 3 0 1 4 0 0 0 0 4 1 3 3 4 1 1 1 3 0 0 5 5 1 1 0 5
 1 5 4 4 4 0 3 0 4 1 1 4 2 4 1 3 4 0 0 4 1 5 1 1 5 5 0 0 3 5 4 1 5 0 3 1 5
 3 5 5 3 1 5 5 0 0 0 4 0 1 1 0 3 4 1 1 1 3 0 0 4 1 5 1 3 4 5 3 1 5 1 1 3 4
 3 4 5 3 3 0 3 0 1 3 0 1 3 0 4 4 3 1 5 0 4 5 0 4 1 5 3 0 0 4 4 3 3 4 5 4 3
 0 3 3 4 5 1 1 4 1 1 5 5 0 0 0 0 4 4 3 0 3 1 1 0 5 4 3 1 5 4 1 4 1 3 1 1 0
 1 4 5 1 5 1 4 0 0 3 1 0 3 6 4 4 1 4 4 1 5 1 4 0 0 0 1 1 5 4 0 0 0 1 0 4 3
 4 1 5 3 1 0 1 3 1 5 3 3 1 1 1 4 3 5 5 3 1 0 5 0 5 0 1 5 4 4 4 3]


[ 9 10 20 25  5 24 18 27 20 11  1  9 19 12 26 27  3  4 24 17  2 23 30 29
  5 23  7 12 15 15  8  6 17 16 21 26 13 22 30 25  0 18 16 18 14  3 29  3
 12  8  5 21  0 13 21 14 16 14 13  1 18 18  0  2  4 28  8 29  7 19 12  1
 15 15  8 16  6 25  9 17 23 11 10  6 30 29 13  5 19 10 22  2  7 27 10 12
 20  4 20 28  7  6  5 15  7 28 23 11  4 28 26 25 25 11  3  9 28  4  4  0
 30 16 18 13  2 28 22 22 27  0 23  6 21 29 18 17  1 16 28 28 24 19  1 11
 24 25 17 17 14  7  1 10 27 30 22 30 22 20 22 28 26 28  6  3 11 28 19 14
 21 30  0 29 24  1 23 23 15 12 11 11  4 18 24 15 10 27  4 26  3 28  6 27
 23 26 22 14 24 22 28  7 19  5  8 20 23 30  7 28 16 25  5  2  7 19 19  6
  7 28  5  4  3 14  1  2  8 30 13 13 10 23  3 28 26 21  3  9 26 18 10 25
  9 16  9  3  2 28 12 21 27 14 25 25  2 14 15 24 28  2  9 26  0 24  0 15
  8  9  5 28 10  0 18 28 21 29 22 12  1 18 25  4 26 28 29  2 28 13 28 29
 10  2  6  5 15 28 14 14 16  4 18 19 22 20 27  0 12 27  5 26 13 11  9 23
  3  8 25 17 28  6 16 28  6 30 27 20 13 19  8 19 20  2  2 28 26 16 18 28
 13 28 17  8 21  1 28  3  2 21 29 11 29 17 13  9 22 28 28 18 13 11  8 28
 28 19  6 11 27 11 25 28  5 22  6 28 21 30  9 10 15  7 24 22 14 25 13 13
  3 28 20  8 28  0 28 17 12 28 16 19 28 16 12 29  9 17 23 10 20 23 24 28
 26 28 30  1  8  7 28 26 23 17 18 12 28 30  6  4  2 10 28  0 17 17  0 27
 30 20 16 21  1 10 29  3 19 12 19  4 16  9 29  1 15 20 11 14 27 28 14 28
 24 20  1  7 21 24 24 28 25 28  1  8  4  5 12  5 27 10 29 18]

In [5]:
# 產生訓練資料集，建立模型與訓練
train_X = pd.DataFrame([Pos_encoder_value,NBApoints_data["Age"],
                        NBApoints_data["2P"],Tm_encoder_value]).T
                        
#train_X = pd.DataFrame([Pos_encoder_value,NBApoints_data["Age"]]).T

NBApoints_linear_model = LinearRegression()
NBApoints_linear_model.fit(train_X, NBApoints_data["3P"])

LinearRegression()

In [7]:
# 預測三分球得球數
NBApoints_linear_model_predict_result= NBApoints_linear_model.predict([[5,28,10,11]])
print('三分球得球數=',"% .4f" % NBApoints_linear_model_predict_result)

三分球得球數=  2.1119

In [8]:
# 計算R-squared與P-value
r_squared = NBApoints_linear_model.score(train_X, NBApoints_data["3P"])
print('R_squared值=',"% .4f" % r_squared)

print("f_regresstion\n")
print("P值=",f_regression(train_X, NBApoints_data["3P"])[1])

R_squared值=  0.3383
f_regresstion

P值= [2.28418914e-30 1.69037260e-01 8.25422767e-07 2.84584085e-01]

四個特徵值的P值:
Pos_encoder_value  2.28418914e-30   P值<0.05  Pos欄位顯著
NBApoints_data["Age"]  1.69037260e-01 P值>0.05  Age欄位不顯著
NBApoints_data["2P"]   8.25422767e-07  P值<0.05  2P欄位顯著
Tm_encoder_value  2.84584085e-01  P值>0.05  Tm欄位不顯著

In [11]:
# 產生訓練資料集，建立模型與訓練
train_X = pd.DataFrame([Pos_encoder_value,
                        NBApoints_data["2P"]]).T
                        
NBApoints_linear_model = LinearRegression()
NBApoints_linear_model.fit(train_X, NBApoints_data["3P"])
# 計算R-squared與P-value
r_squared = NBApoints_linear_model.score(train_X, NBApoints_data["3P"])
print('R_squared值=',"% .4f" % r_squared)

print("f_regresstion\n")
print("P值=",f_regression(train_X, NBApoints_data["3P"])[1])

R_squared值=  0.3248
f_regresstion

P值= [2.28418914e-30 8.25422767e-07]